[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    # paste is unmaintained but still works - waiting on Bevy to update
    "RUSTSEC-2024-0436"
]

[licenses]
allow = [
    "GPL-3.0-or-later",
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Unicode-3.0",
    "CC0-1.0",
    "ISC",
    "Zlib"
]

confidence-threshold = 0.8

[bans]
multiple-versions = "allow"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
